### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by ghost** [wadpac/SleepStageClassification#1]
Is there a "quickstart" document anywhere, otherwise I'll study the code.

I have XYZ binary raw accel sleep data and want to classify sleep stages (light, deep.., REM).

**Comment by vincentvanhees** [comment]
Sorry, this was still on my to do list... I have now updated the README with better documentation: https://github.com/wadpac/SleepStageClassification/tree/master/ggir_ext

Please note that this does not do sleep stage classification, but only sleep/wake/non-wear classification. In our paper we showed that sleep stage classification is not realistic based on accelerometer data. Therefore, we did not consider it a good idea to release those models.

**Comment by ghost** [comment]
Thank you very much for your update with "only sleep/wake/non-wear classification."

Out of curiosity, was module plot_sleep_stages.py for some other project then?
It has "sleep_stages = ['Wake','NREM1','NREM2','NREM3','REM','Nonwear','Unlabeled']"
and so I jumped to the conclusion there was stage classification.

**Comment by ghost** [comment]
Out of further curiosity, what was story behind naming this project SleepStageClassification ?
:-D

**Comment by vincentvanhees** [comment]
> Out of curiosity, was module plot_sleep_stages.py for some other project then?
> It has "sleep_stages = ['Wake','NREM1','NREM2','NREM3','REM','Nonwear','Unlabeled']"

This repository is an archive of the code used as part the research done for our [paper](https://www.nature.com/articles/s41598-020-79217-x). It is not really intended to be software library as such.  In the paper we explored the potential of sleep stage classification and the code you found correspond to those experiments.

> Out of further curiosity, what was story behind naming this project SleepStageClassification ?

The project started ambitiously with an attempt to classify sleep stages. When we realised that we could not even derive a moderately accurate sleep stage classifier, we shifted focus to sleep-wake-nonwear classification. So, the name 'SleepStageClassification' is a bit outdated, and I can see that this could be confusing.

We can rename the repository and GitHub should then redirect visitors from the old to the new url.
For example we could rename this repository to: Sundararajan-SleepClassification-2021

@kalaivani-s  Are you ok with this name change?

**Comment by vincentvanhees** [comment]
> We can rename the repository and GitHub should then redirect visitors from the old to the new url.
> For example we could rename this repository to: Sundararajan-SleepClassification-2021

I have now done this to avoid confusion about what this repository is about.
