### ISSUE TITLE
Results not being written to csv output

### ISSUE THREAD

**Issue by m-patterson** [wadpac/SleepStageClassification#2]
Thanks for sharing this great package!

When I run the package in 'binary' mode, I can see the 'wake_sleep' results when I load the RData file out of the 'basic' folder:
![image](https://user-images.githubusercontent.com/16383946/111488378-8e80d880-870f-11eb-8acd-bcf3a48bffea.png)

However, I do not see the 'wake_sleep' results in the csv file in the 'csv' folder:
![image](https://user-images.githubusercontent.com/16383946/111488468-a7898980-870f-11eb-87fa-a2e97fafffb0.png)

Also, when I try to run the package in 'multiclass' mode I get a TypeError: unsupported operand type(s) for /: 'NoneType' and 'float' on line 54 from get_sleep_stage.py ( y_pred = y_pred/float(nfolds) )

Here is the way I am calling 'multiclass', do I need to change the input for 'colnames'?
![image](https://user-images.githubusercontent.com/16383946/111491106-f7695000-8711-11eb-80cf-5b75cf36dfb0.png)

**Comment by vincentvanhees** [comment]
Initially the project focused on multiclass but once the research indicated that multiclass was not giving any promising results our focus shifted back to binary sleep classification. The models we uploaded to Zenodo are binary models only. We intentionally did not include the poor multiclass model as we were afraid that researchers would actually start using it in their research.
